name: GoTask Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Run vet
      run: go vet ./...

    - name: Run staticcheck
      run: |
        wget -O staticcheck.tgz https://github.com/dominikh/go-tools/releases/download/2021.1/staticcheck_linux_amd64.tar.gz
        sudo tar -xzf staticcheck.tgz
        ./staticcheck/staticcheck --version
        ./staticcheck/staticcheck -checks=all ./...
    - name: Test
      run: go test -race -v  ./...
